# Generated by Django 2.1.1 on 2019-05-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190509_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usernumber',
            table='user_number',
        ),
    ]
