# Generated by Django 2.1.1 on 2019-05-23 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20190523_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 19, 9, 58, 909431)),
        ),
    ]
