# Generated by Django 2.1.1 on 2019-05-26 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20190523_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 6, 0, 52, 743285)),
        ),
    ]
