# Generated by Django 2.1.1 on 2019-05-28 04:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0008_auto_20190526_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAWSBucketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 4, 50, 37, 939994)),
        ),
    ]
