# Generated by Django 2.1.1 on 2019-05-28 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20190528_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userawsbucketinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 6, 17, 26, 944769)),
        ),
        migrations.DeleteModel(
            name='UserAWSBucketInfo',
        ),
    ]
