# Generated by Django 2.1.1 on 2019-05-29 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20190528_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 5, 17, 36, 510289)),
        ),
    ]
