# Generated by Django 2.1.1 on 2019-04-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://63d50cfa.ngrok.io/callback'),
        ),
    ]
