# Generated by Django 2.1.1 on 2019-04-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0002_auto_20190414_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://b84ca433.ngrok.io/callback'),
        ),
    ]
