# Generated by Django 2.1.1 on 2019-04-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0003_auto_20190416_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://54aac248.ngrok.io/callback'),
        ),
    ]
