# Generated by Django 2.1.1 on 2019-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0004_auto_20190418_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://2602c2b3.ngrok.io/callback'),
        ),
    ]
