# Generated by Django 2.1.1 on 2019-04-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0006_auto_20190427_1928'),
        ('bandwidth', '0006_auto_20190425_1006'),
    ]

    operations = [
    ]
