# Generated by Django 2.1.1 on 2019-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0007_merge_20190427_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://02c76101.ngrok.io/callback'),
        ),
    ]
