# Generated by Django 2.1.1 on 2019-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0008_auto_20190427_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://da55b18c.ngrok.io/callback'),
        ),
    ]
