# Generated by Django 2.1.1 on 2019-04-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0009_auto_20190428_0937'),
        ('bandwidth', '0009_auto_20190430_1132'),
    ]

    operations = [
    ]
