# Generated by Django 2.1.1 on 2019-05-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0010_merge_20190430_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://296fe8a1.ngrok.io/callback'),
        ),
    ]
