# Generated by Django 2.1.1 on 2019-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0011_auto_20190501_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://1d6b818c.ngrok.io/callback'),
        ),
    ]
