# Generated by Django 2.1.1 on 2019-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0012_auto_20190501_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://383b22d1.ngrok.io/callback'),
        ),
    ]
