# Generated by Django 2.1.1 on 2019-05-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0013_auto_20190502_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://9bd7f06a.ngrok.io/callback'),
        ),
    ]
