# Generated by Django 2.1.1 on 2019-05-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0014_auto_20190502_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://d2d7e2c1.ngrok.io/callback'),
        ),
    ]
