# Generated by Django 2.1.1 on 2019-05-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0016_auto_20190506_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://617d4c8f.ngrok.io/callback'),
        ),
    ]
