# Generated by Django 2.1.1 on 2019-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0018_auto_20190523_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackurlinfo',
            name='url',
            field=models.URLField(default='http://617d4c8f.ngrok.io/callback'),
        ),
    ]
